services:
  sosu-frontend:
    build: .
    ports:
      - "3000:3000"
    container_name: sosu-frontend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - web

networks:
  web:
    external: true

